databases:
  - name: terminus
    plan: free
    databaseName: terminus
    postgresMajorVersion: 18
    user: terminus

services:
  - type: web
    name: terminus-web
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /up
    runtime: docker
    envVars:
      - key: API_URI
        value: $RENDER_EXTERNAL_URL
      - key: HANAMI_PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: terminus
          property: connectionString
      - key: KEYVALUE_URL
        fromService:
          type: keyvalue
          name: terminus-cache
          property: connectionString

  - type: worker
    name: terminus-worker
    plan: free
    autoDeployTrigger: commit
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: terminus
          property: connectionString
      - key: KEYVALUE_URL
        fromService:
          type: keyvalue
          name: terminus-cache
          property: connectionString
    dockerCommand: bundle exec sidekiq -r ./config/sidekiq.rb

  - type: keyvalue
    name: terminus-cache
    plan: free
    ipAllowList: []
